  sut:
    image: quay.io/mozmar/kuma_base
    user: ${UID:-0}
    volumes:
      - ./:/app
    command: py.test --nomigrations kuma
    depends_on:
      - memcached
      - mysql
      - elasticsearch
    environment:
      - DATABASE_URL=mysql://root:kuma@mysql:3306/developer_mozilla_org
      - ES_URLS=elasticsearch:9200
      - MEMCACHE_SERVERS=memcached:11211
      - PYTHONDONTWRITEBYTECODE=1
